### ISSUE TITLE
starting attributes

### ISSUE THREAD

**Issue by thareUSGS** [pds-data-dictionaries/ldd-msss_cam_mh#1]
Per Bob. D. (for M2020).

recommended attributes to copy from

MSSS_Camera_Mini_Header
-   img_surface:camera_product_id
-   msss_cam_mh:magic_initial - Hexadecimal value that indicates the start of the mini-header
-   msss_cam_mh:magic_final - Hexadecimal value that indicates the end of the mini-header
-   msn:spacecraft_clock_start
-   img:detector_erase_count
-   img_surface:instrument_mode_id
-   img:Filter   (just uses filter_number)
-   img:Exposure_Parameters (uses exposure_duration_count, exposure_type)
-   img:Subframe_Parameters (uses first_line ,first_sample, lines, samples)
-   img:Focus_Parameters (uses focus_mode, focus_position_count, focus_step_size, focus_steps
-   img:Autoexposure_Parameters (uses data_cut, pixel_fraction, percent, max count)
-   img:Image_Compression_Parameters (uses class, type, quality, and JPEG quality and color subsampling mode)
-   img:Companding_Parameters (uses companding_method)
-   img:Instrument_Device_State
-   img_surface:instrument_serial_number
-   geom:Device_Motor_Counts
-   img:analog_offset
-   msss_cam_mh:initial_size - Initially-allocated size of data product

**Comment by rgdeen** [comment]
Note that my current recommendation is to use msss_cam_mh: for the attributes (like msss_cam_mh:spacecraft_clock_start) and use cross-dictionary references only for the classes (like img:Filter).

**Comment by rgdeen** [comment]
Below is the current example.

    <Mission_Area>
      <msss_cam_mh:MSSS_Camera_Mini_Header>
        <msss_cam_mh:camera_product_id>2925</msss_cam_mh:camera_product_id>
        <msss_cam_mh:magic_initial>FF00F0CA</msss_cam_mh:magic_initial>
        <msss_cam_mh:magic_final>1010CC28</msss_cam_mh:magic_final>
        <msss_cam_mh:spacecraft_clock_start>405851637</msss_cam_mh:spacecraft_clock_start>
        <msss_cam_mh:detector_erase_count>2047</msss_cam_mh:detector_erase_count>
        <msss_cam_mh:instrument_mode_id>MODE_0X0009 10 MHz</msss_cam_mh:instrument_mode_id>
        <msss_cam_mh:filter_number>0</msss_cam_mh:filter_number>
        <msss_cam_mh:exposure_duration_count>349</msss_cam_mh:exposure_duration_count>
        <msss_cam_mh:first_sample>129</msss_cam_mh:first_sample>
        <msss_cam_mh:first_line>33</msss_cam_mh:first_line>
        <msss_cam_mh:samples>1408</msss_cam_mh:samples>
        <msss_cam_mh:lines>1152</msss_cam_mh:lines>
        <msss_cam_mh:Focus>
          <msss_cam_mh:focus_mode>AUTOFOCUS</msss_cam_mh:focus_mode>
          <msss_cam_mh:focus_position>2274</msss_cam_mh:focus_position>
          <msss_cam_mh:focus_step_size>6</msss_cam_mh:focus_step_size>
          <msss_cam_mh:focus_step_count>1</msss_cam_mh:focus_step_count>
        </msss_cam_mh:Focus>
        <msss_cam_mh:Exposure>
          <msss_cam_mh:exposure_duration_count>349</msss_cam_mh:exposure_duration_count>
          <msss_cam_mh:exposure_type>AUTO</msss_cam_mh:exposure_type>
          <msss_cam_mh:Autoexposure>
            <msss_cam_mh:processing_algorithm>Maki 2003</msss_cam_mh:processing_algorithm>
            <msss_cam_mh:auto_exposure_data_cut>150</msss_cam_mh:auto_exposure_data_cut>
            <msss_cam_mh:auto_exposure_percent>10</msss_cam_mh:auto_exposure_percent>
            <msss_cam_mh:auto_exposure_pixel_fraction>2</msss_cam_mh:auto_exposure_pixel_fraction>
            <msss_cam_mh:max_auto_exposure_iteration_count>8</msss_cam_mh:max_auto_exposure_iteration_count>
          </msss_cam_mh:Autoexposure>
        </msss_cam_mh:Exposure>
        <msss_cam_mh:Onboard_Compression>
          <msss_cam_mh:onboard_compression_mode>2</msss_cam_mh:onboard_compression_mode>
          <msss_cam_mh:onboard_compression_quality>0.95</msss_cam_mh:onboard_compression_quality>
        </msss_cam_mh:Onboard_Compression>
        <msss_cam_mh:Companding>
          <msss_cam_mh:processing_algorithm>MMM_LUT0</msss_cam_mh:processing_algorithm>
        </msss_cam_mh:Companding>
        <msss_cam_mh:Instrument_State>
          <msss_cam_mh:Instrument_State_Index>
            <msss_cam_mh:index_id>SPARE</msss_cam_mh:index_id>
            <msss_cam_mh:index_value_string>FALSE</msss_cam_mh:index_value_string>
          </msss_cam_mh:Instrument_State_Index>
          <msss_cam_mh:Instrument_State_Index>
            <msss_cam_mh:index_id>UV_LED</msss_cam_mh:index_id>
            <msss_cam_mh:index_value_string>FALSE</msss_cam_mh:index_value_string>
          </msss_cam_mh:Instrument_State_Index>
          <msss_cam_mh:Instrument_State_Index>
            <msss_cam_mh:index_id>VIS1_LED</msss_cam_mh:index_id>
            <msss_cam_mh:index_value_string>FALSE</msss_cam_mh:index_value_string>
          </msss_cam_mh:Instrument_State_Index>
          <msss_cam_mh:Instrument_State_Index>
            <msss_cam_mh:index_id>VIS2_LED</msss_cam_mh:index_id>
            <msss_cam_mh:index_value_string>FALSE</msss_cam_mh:index_value_string>
          </msss_cam_mh:Instrument_State_Index>
          <msss_cam_mh:Instrument_State_Index>
            <msss_cam_mh:index_id>SPARE</msss_cam_mh:index_id>
            <msss_cam_mh:index_value_string>FALSE</msss_cam_mh:index_value_string>
          </msss_cam_mh:Instrument_State_Index>
          <msss_cam_mh:Instrument_State_Index>
            <msss_cam_mh:index_id>MASTCAM_FILTER_HALL_STATE</msss_cam_mh:index_id>
            <msss_cam_mh:index_value_string>FALSE</msss_cam_mh:index_value_string>
          </msss_cam_mh:Instrument_State_Index>
          <msss_cam_mh:Instrument_State_Index>
            <msss_cam_mh:index_id>MAHLI_COVER_HALL_STATE</msss_cam_mh:index_id>
            <msss_cam_mh:index_value_string>TRUE</msss_cam_mh:index_value_string>
          </msss_cam_mh:Instrument_State_Index>
          <msss_cam_mh:Instrument_State_Index>
            <msss_cam_mh:index_id>FOCUS_HALL_STATE</msss_cam_mh:index_id>
            <msss_cam_mh:index_value_string>TRUE</msss_cam_mh:index_value_string>
          </msss_cam_mh:Instrument_State_Index>
        </msss_cam_mh:Instrument_State>
        <msss_cam_mh:instrument_serial_number>3003</msss_cam_mh:instrument_serial_number>
        <msss_cam_mh:Articulation_Dev_Position>
          <msss_cam_mh:Articulation_Dev_Position_Index>
            <msss_cam_mh:index_id>FOCUS</msss_cam_mh:index_id>
            <msss_cam_mh:index_value_number>2274</msss_cam_mh:index_value_number>
          </msss_cam_mh:Articulation_Dev_Position_Index>
          <msss_cam_mh:Articulation_Dev_Position_Index>
            <msss_cam_mh:index_id>FILTER</msss_cam_mh:index_id>
            <msss_cam_mh:index_value_number>0</msss_cam_mh:index_value_number>
          </msss_cam_mh:Articulation_Dev_Position_Index>
        </msss_cam_mh:Articulation_Dev_Position>
        <msss_cam_mh:analog_offset>117</msss_cam_mh:analog_offset>
        <msss_cam_mh:initial_size>1622080</msss_cam_mh:initial_size>
        <msss_cam_mh:Instrument_Mode>
          <msss_cam_mh:Instrument_Mode_Index>
            <msss_cam_mh:index_id>SPARE</msss_cam_mh:index_id>
            <msss_cam_mh:index_value_string>0</msss_cam_mh:index_value_string>
          </msss_cam_mh:Instrument_Mode_Index>
          <msss_cam_mh:Instrument_Mode_Index>
            <msss_cam_mh:index_id>CCD_STATE</msss_cam_mh:index_id>
            <msss_cam_mh:index_value_string>0</msss_cam_mh:index_value_string>
          </msss_cam_mh:Instrument_Mode_Index>
          <msss_cam_mh:Instrument_Mode_Index>
            <msss_cam_mh:index_id>LED1_CONTROL</msss_cam_mh:index_id>
            <msss_cam_mh:index_value_string>0</msss_cam_mh:index_value_string>
          </msss_cam_mh:Instrument_Mode_Index>
          <msss_cam_mh:Instrument_Mode_Index>
            <msss_cam_mh:index_id>LED2_CONTROL</msss_cam_mh:index_id>
            <msss_cam_mh:index_value_string>0</msss_cam_mh:index_value_string>
          </msss_cam_mh:Instrument_Mode_Index>
          <msss_cam_mh:Instrument_Mode_Index>
            <msss_cam_mh:index_id>LED3_CONTROL</msss_cam_mh:index_id>
            <msss_cam_mh:index_value_string>0</msss_cam_mh:index_value_string>
          </msss_cam_mh:Instrument_Mode_Index>
          <msss_cam_mh:Instrument_Mode_Index>
            <msss_cam_mh:index_id>VIDEO_EXPOSURE</msss_cam_mh:index_id>
            <msss_cam_mh:index_value_string>0</msss_cam_mh:index_value_string>
          </msss_cam_mh:Instrument_Mode_Index>
          <msss_cam_mh:Instrument_Mode_Index>
            <msss_cam_mh:index_id>CLKDIV2</msss_cam_mh:index_id>
            <msss_cam_mh:index_value_string>1</msss_cam_mh:index_value_string>
          </msss_cam_mh:Instrument_Mode_Index>
          <msss_cam_mh:Instrument_Mode_Index>
            <msss_cam_mh:index_id>LONG_INTEGRATION_MODE</msss_cam_mh:index_id>
            <msss_cam_mh:index_value_string>0</msss_cam_mh:index_value_string>
          </msss_cam_mh:Instrument_Mode_Index>
          <msss_cam_mh:Instrument_Mode_Index>
            <msss_cam_mh:index_id>TEST_MODE</msss_cam_mh:index_id>
            <msss_cam_mh:index_value_string>0</msss_cam_mh:index_value_string>
          </msss_cam_mh:Instrument_Mode_Index>
          <msss_cam_mh:Instrument_Mode_Index>
            <msss_cam_mh:index_id>CLKDIV1</msss_cam_mh:index_id>
            <msss_cam_mh:index_value_string>1</msss_cam_mh:index_value_string>
          </msss_cam_mh:Instrument_Mode_Index>
        </msss_cam_mh:Instrument_Mode>
      </msss_cam_mh:MSSS_Camera_Mini_Header>
    </Mission_Area>

**Comment by rgdeen** [comment]
in that example, cross-dictionary references (if we do that) should be: Focus, Exposure, Onboard_Compression, Companding, Instrument_State, Articulation_Dev_Position.

Instrument_Mode could be changed to something else to be compatible with img: if we wanted.

**Comment by thareUSGS** [comment]
I verified ldd-msss_cam_mh should be considered a discipline dictionary thus is can borrow directly from IMG without needing to duplicate many attributes.

**Comment by rgdeen** [comment]
Seriously??!!!!!   It's discipline???  I mean, I'm okay with that, just pretty shocked.

But even still, I thought we had to get approval for cross-dict sharing.  The main use case we went with to the tech group was using geom items in cart and img... which are both discipline.

But hey, if you think we can do it, I'm not going to complain!!

In which case yeah we should change instrument_mode to something else.  Suggestions?

**Comment by rgdeen** [comment]
maybe mode -> just more items in instrument_state?  Does that make sense?

The source keywords are:
```
INSTRUMENT_STATE=('FALSE', 'FALSE', 'FALSE', 'FALSE', 'FALSE', 'FALSE', 
'TRUE', 'TRUE')
INSTRUMENT_STATE_NAME=('SPARE', 'UV_LED', 'VIS1_LED', 'VIS2_LED', 'SPARE', 
'MASTCAM_FILTER_HALL_STATE', 'MAHLI_COVER_HALL_STATE', 'FOCUS_HALL_STATE')

INSTRUMENT_MODE=(0, 0, 0, 0, 0, 0, 1, 0, 0, 1)
INSTRUMENT_MODE_NAME=('SPARE', 'CCD_STATE', 'LED1_CONTROL', 'LED2_CONTROL', 
'LED3_CONTROL', 'VIDEO_EXPOSURE', 'CLKDIV2', 'LONG_INTEGRATION_MODE', 
'TEST_MODE', 'CLKDIV1')
```
which is why I said mode but perhaps there's no real difference...?

**Comment by jordanpadams** [comment]
@thareUSGS what Bob is talking about here is that in order for the dictionaries to be valid, you must "expose" the class using the `element_flag` attribute. Per the discussions at the last tech session, we discussed some sort of approval to make sure people weren't just making everything inheritable across dictionaries.

**Comment by thareUSGS** [comment]
@rgdeen So within IMG there is an Instrument_State having the attributes of (Device_Component_States, Device_Currents, Device_Motor_Counts, Device_Temperatures, Device_Voltages). 
https://github.com/pds-data-dictionaries/ldd-img/blob/7087a51bd8ab213f5907d6a5ab01df0d0f830336/PDS4_IMG_IngestLDD.xml#L3916

 At first glance it didn't seem to be able to handle the above STATEs and MODEs). But perhaps it can.

@jordanpadams Is this perhaps what this section was meant for? Here are a couple entries for Bob's thread above. Can this (should this) be used for both INSTRUMENT_STATE and INSTRUMENT_MODE? 

```xml
   <Instrument_State>
      <Device_Component_States>
         <Device_Component_State>
            <Device_Parameters>
               <device_name>SPARE</device_name>
            </Device_Parameters>
            <device_state>False</device_state>
         </Device_Component_State>
         <Device_Component_State>
            <Device_Parameters>
               <device_name>UV_LED</device_name>
            </Device_Parameters>
            <device_state>False</device_state>
         </Device_Component_State>
      </Device_Component_States>
   </Instrument_State>
```
so device_state is only a ASCII_Short_String_Collapsed.

more about Device_Parameters: https://github.com/pds-data-dictionaries/ldd-img/blob/7087a51bd8ab213f5907d6a5ab01df0d0f830336/PDS4_IMG_IngestLDD.xml#L3373

**Comment by jordanpadams** [comment]
@thareUSGS that seems like a logical place for it.

**Comment by rgdeen** [comment]
I think Device_Component_State could be used for both?

I don't think I'm bothered if the value type is a string but the actual values are numbers.  The other way around would be a problem of course.  I mean, we could add something like device_state_int or device_state_float but that just seems overly pedantic.

@jordanpadams so should we just go ahead and DO it?  Easier for forgiveness than permission kind of thing?  Especially for the ones referencing img... the one that references geom could be more problematic, and we could just copy that if needed.

**Comment by thareUSGS** [comment]
obviously those above would need the "img:" inline within a MSSS_Camera_Mini_Header header.

**Comment by rgdeen** [comment]
okay you're the boss!  ;-)

So I think the summary is...

* Use via cross-dir the following classes from img:  Focus, Exposure, Onboard_Compression, Companding, and Instrument_State.

* switch Articulation_Dev_Position to Device_Motor_Counts under Instrument_State (thus avoiding geom).

* Switch both Instrument_State and Instrument_Mode to Device_Component_States under Instrument_State

* Move dictionary to Discipline instead of Mission area.

Is that about right?

**Comment by rgdeen** [comment]
So here's a complete example:

```

**Comment by rgdeen** [comment]
yeah I think I like that one

**Comment by thareUSGS** [comment]
@rgdeen starting to look good. But I think device_id needs to be wrapped in Device_Parameters. 

```xml
        <img:Instrument_State>
          <img:Device_Component_States>
            <img:Device_Component_State>
              <img:Device_Parameters>
                <img:device_id>SPARE</img:device_id>
              </img:Device_Parameters>
              <img:device_state>FALSE</img_device_state>
            </img:Device_Component_State>
            <img:Device_Component_State>
              <img:Device_Parameters>
                <img:device_id>UV_LED</img:device_id>
              </img:Device_Parameters>
              <img:device_state>FALSE</img_device_state>
            </img:Device_Component_State>
            <img:Device_Component_State>
              <img:Device_Parameters>
                 <img:device_id>VIS1_LED</img:device_id>
              </img:Device_Parameters>
              <img:device_state>FALSE</img_device_state>
            </img:Device_Component_State>
```

I think I am reading that class correctly: https://github.com/pds-data-dictionaries/ldd-img/blob/7087a51bd8ab213f5907d6a5ab01df0d0f830336/PDS4_IMG_IngestLDD.xml#L3272

**Comment by rgdeen** [comment]
I don't think so.  The XSD (easier for me to read) looks like this:
```  <xs:complexType name="Device_Component_State">
    <xs:annotation>
      <xs:documentation>The Device_Component_State class describes the
        state of one component of an imaging instrument or other imaging
        device. The meaning of "state" is
        device-specific.</xs:documentation>
    </xs:annotation>
    <xs:complexContent>
      <xs:extension base="img:Device_Parameters">
        <xs:sequence>
          <xs:element name="device_state" type="img:device_state" minOccurs="0" maxOccurs="1"> </xs:element>
        </xs:sequence>
      </xs:extension>
    </xs:complexContent>
  </xs:complexType>
```
The xs:extension means as I understand it you're including everyting in there implicitly... so you don't see Device_Parameters in the actual xml but you include all its children in that group.  At least that's the way it's worked for others... hopefully the definition isn't wrong here?

geom uses this all over the place, they have a whole hierarchy of quaternion classes for example that you never see in the xml.

**Comment by thareUSGS** [comment]
Yep you got me. And that look much better in the label. In local data dictionary (LDD) speak, that must be the meaning of "parent_of" -- need to remember that. Good to review the XSD.

**Comment by thareUSGS** [comment]
@rgdeen I could use some help reviewing this and some definitions (look for TBD). Also the min/max allowed. see: https://github.com/pds-data-dictionaries/ldd-msss_cam_mh/blob/master/src/PDS4_MSSS_CAM_MH_IngestLDD.xml

**Comment by thareUSGS** [comment]
I've been stuck here for a bit building with IMG. Need to track down lddtool or setting issue...

**Comment by rgdeen** [comment]
We'll see when we validate.  A quick glance seems to show it's okay.  A bit surprised that the magics and cdpid are required, but that's okay I think.

**Comment by thareUSGS** [comment]
validating with latest IMG release on github, but needs to be updated to PDS4 repository after next issue resolved.
